steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/scenario-arm-image', './Dockerfile_Scenario_Arm']
      timeout: '10m'

images:
    - 'gcr.io/$PROJECT_ID/scenario-arm-image'

volumes:
    - name: 'results'
      path: '~/git/sferes2/results'

timeout: '20m'
