steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/collectball-qd-image', '-f' ,'./Dockerfile_Scenario_Arm', '.']
      timeout: '600s'

images:
    - 'gcr.io/$PROJECT_ID/scenario-arm-image'
