steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/scenario-arm-image', './Dockerfile_Scenario_Arm']
      timeout: '600s'
      volumes:
        - name: 'results'
          path: '/root/git/sferes2/build/exp/modular_QD/'

images:
    - 'gcr.io/$PROJECT_ID/scenario-arm-image'
