steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/collectball-qd-image', './Dockerfile_CollectBall_QD']
      timeout: '10m'
      volumes:
        - name: 'results'
          path: '~/git/sferes2/results'

images:
    - 'gcr.io/$PROJECT_ID/collectball-qd-image'

timeout: '20m'
